config/routes.rb
Rails.application.routes.draw do
  get "comments/new"
  get "comments/create"

  devise_for :users

  resources :users, only: [ :index, :show, :edit, :update ] do
    member do
      post "accept_follow_request"
      post "reject_follow_request"
      delete "unfollow"
    end
  end

  resources :posts, only: [ :new, :create ]

  resources :follow_requests, only: [ :create ]

  resources :likes, only: [ :create, :destroy ]

  resources :comments, only: [ :create ]


  root to: "posts#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: "user_id"
  belongs_to :post

  validates :body, presence: true, length: { maximum: 8000 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(comment_params[:post_id])
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.turbo_stream
      else
        format.html { redirect_to root_path, status: :unprocessable_entity }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :user_id, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def new_comment
    Comment.new
  end
end

app/views/comments/_comment.html.erb
<div class="commentContainer">
  <%= user_links(comment.author, class: "userLink") %>
  <div class="commentBody">
    <%= simple_format(comment.body) %>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="commentFormContainer" data-controller= "post-button">
  <%= form_with model: comment, url: comments_path, class: "commentForm" do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :post_id, value: post.id %>
    <%= f.text_area :body, data: { target: 'post-button.textField' }, class: "input", id: "comment_input"%>
    <%= f.submit "Comment", data: { action: "click->post-button#clear_fields", target: "postButton" }, class: "submitBtn" %>
  <% end %>
</div>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append "comments_#{@post.id}", @comment %>