config/routes.rb
Rails.application.routes.draw do
  get "comments/new"
  get "comments/create"

  devise_for :users

  resources :users, only: [ :index, :show, :edit, :update ] do
    member do
      post "accept_follow_request"
      post "reject_follow_request"
      delete "unfollow"
    end
  end

  resources :posts, only: [ :new, :create ]

  resources :follow_requests, only: [ :create ]

  resources :likes, only: [ :create, :destroy ]

  resources :comments, only: [ :create ]


  root to: "posts#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/follow_request.rb
class FollowRequest < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :recipient, class_name: "User", foreign_key: "recipient_id"

  def self.create_request(sender, recipient)
    create(sender: sender, recipient: recipient, status: "pending")
  end

  def self.delete_request(sender, recipient)
    find_by(sender: sender, recipient: recipient)&.destroy
  end
end

app/controllers/follow_requests_controller.rb
class FollowRequestsController < ApplicationController
  def create
    recipient = User.find(params[:recipient_id])
    FollowRequest.create_request(current_user, recipient)
  end
end

app/helpers/follow_requests_helper.rb
require "pry-byebug"

module FollowRequestsHelper
  def follow_request_decision_form(url, request, button_text, stimulus_action, stimulus_target)
    form_with(url: url, method: :post) do |f|
      concat f.hidden_field(:follower_id, value: request.sender.id)
      concat f.hidden_field(:request_id, value: request.id)
      concat f.submit(button_text, data: {
        action: stimulus_action, target: stimulus_target },
        class: "submitBtn", id: "reqBtn")
    end
  end

  def follow_request_form(user, sent_follow_requests)
    unless sent_follow_requests.include?(user.id)
      form_with(url: follow_requests_path, method: :post) do |f|
        concat f.hidden_field :recipient_id, value: user.id
        concat f.submit "Send Follow Request", data: { controller: "follow-buttons", action: "click->follow-buttons#change_request_button", target: "follow-buttons.button" }, class: "submitBtn"
      end
    end
  end

  def unfollow_button(user)
    if current_user.followees.include?(user)
      form_with url: unfollow_user_path(user), method: :delete do |f|
        concat f.hidden_field(:followee_id, value: user.id)
        concat f.submit "Unfollow", class: "submitBtn"
      end
    end
  end
end

app/views/follow_requests/_index.html.erb
<% if received_follow_requests.any? %>
  <div class="reqListContainer">
      <h2>You have some follow requests pending:</h2>

      <% received_follow_requests.each do |req| %>
        <div class="reqContainer">
          <%= user_links(req.sender, class: "userLink")%>

          <!--Buttons that allow the current_user to accept or reject a FollowRequest. 
          They use helpers from follow_requests_helper.-->
          <div data-controller= "follow-buttons" class="reqBtnContainer">
            <%= follow_request_decision_form(accept_follow_request_user_path(req.sender.id), 
                                            req, 
                                            "Accept", 
                                            "click->follow-buttons#change_accept_button", 
                                            "follow-buttons.acceptButton") %>

            <%= follow_request_decision_form(reject_follow_request_user_path(req.sender.id), 
                                            req, 
                                            "Delete", 
                                            "click->follow-buttons#change_reject_button", 
                                            "follow-buttons.rejectButton") %>
          </div>
        </div>
    <%end%>
  </div>
<% end %>